name: Create Archive
on:
  push:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: tag number
        run: echo ${{ github.event.release.tag_name }}
      - name: list contents
        run: ls -lart
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-${{ github.event.release.tag_name }}.zip
          exclusions: '*.git* install*.* LICENSE .gitignore'
